"""Keep the always-loaded Skill body lean and domain retrieval selective."""

import os
import subprocess
import sys
import zipfile
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[2]
skill = (ROOT / "SKILL.md").read_text(encoding="utf-8")
failures: list[str] = []

if len(skill.splitlines()) > 180:
    failures.append("SKILL.md exceeds 180 lines")
if len(skill) > 8500:
    failures.append("SKILL.md exceeds 8,500 characters")
if not any(marker in skill for marker in ("Load one stage reference", "每次只加载一个有效切片")):
    failures.append("SKILL lost progressive-disclosure instruction")
if "scripts/query_domain.py --domain <pack>" not in skill:
    failures.append("SKILL loads full domain coverage instead of one compact record")
maintainer_files = [
    path for path in (ROOT / "maintainer").rglob("*")
    if path.is_file() and "__pycache__" not in path.parts and path.suffix != ".pyc"
]
maintainer_bytes = sum(path.stat().st_size for path in maintainer_files)
if len(maintainer_files) > 56:
    failures.append(f"maintainer lab contains {len(maintainer_files)} files; expected <=56")
if maintainer_bytes > 475_000:
    failures.append(f"maintainer lab contains {maintainer_bytes} bytes; expected <=475000")
cli = (ROOT / "scripts/ai_delivery_spec_cli.py").read_text(encoding="utf-8")
fast_slice = cli.split("fast_commands: list[list[str]] = [", 1)[-1].split(
    "release_only_commands: list[list[str]] = [", 1
)[0]
fast_command_count = fast_slice.count("[sys.executable")
if fast_command_count > 12:
    failures.append(f"default fast check runs {fast_command_count} commands; expected <=12")


probe = subprocess.run(
    [sys.executable, str(ROOT / "scripts/query_domain.py"), "--domain", "oa"],
    cwd=ROOT,
    text=True,
    encoding="utf-8",
    errors="replace",
    capture_output=True,
    check=False,
    env={**os.environ, "PYTHONIOENCODING": "cp1252"},
)
if probe.returncode != 0:
    failures.append("OA compact-domain query failed: " + probe.stdout + probe.stderr)
elif len(probe.stdout) > 5000:
    failures.append("OA compact-domain query exceeds 5,000 characters")
for marker in (
    "domain_id: oa", "maturity: contract_tested", "production_claim: prohibited",
    "KS-OA-WEAVER-WHITEPAPER", "KS-OA-DINGTALK-OSS", "KS-OA-FEISHU-OSS",
):
    if marker not in probe.stdout:
        failures.append(f"OA compact-domain query misses {marker!r}")

archive_path = ROOT.parent / f".ads-runtime-budget-{os.getpid()}.zip"
archive_path.unlink(missing_ok=True)
try:
    package = subprocess.run(
        [
            sys.executable, str(ROOT / "maintainer/tools/build_runtime_package.py"),
            "--output", str(archive_path), "--check",
        ],
        cwd=ROOT, text=True, encoding="utf-8", errors="replace", capture_output=True, check=False,
    )
    if package.returncode != 0:
        failures.append("runtime package build failed: " + package.stdout + package.stderr)
    elif not archive_path.is_file():
        failures.append("runtime package archive was not created")
    else:
        with zipfile.ZipFile(archive_path) as archive:
            names = archive.namelist()
            runtime_manifest = yaml.safe_load(archive.read("runtime-manifest.json"))
        polluted = [name for name in names if "__pycache__" in name or name.endswith((".pyc", ".pyo"))]
        if polluted:
            failures.append("runtime package contains generated bytecode: " + ", ".join(polluted))
        runtime_budget = yaml.safe_load((ROOT / "maintainer/runtime-package.yaml").read_text(encoding="utf-8"))["max_files"]
        if len(names) > runtime_budget + 1:  # configured source budget + generated manifest
            failures.append(f"runtime zip contains {len(names)} entries; expected <={runtime_budget + 1}")
        if not isinstance(runtime_manifest.get("source_worktree_dirty"), bool):
            failures.append("runtime manifest does not disclose whether the source worktree was dirty")
        if runtime_manifest.get("source_worktree_dirty") and not str(runtime_manifest.get("source_commit", "")).endswith("-dirty"):
            failures.append("dirty runtime package reports a clean-looking source_commit")
finally:
    archive_path.unlink(missing_ok=True)

if failures:
    raise SystemExit("\n".join(failures))
print(
    f"PASS: SKILL={len(skill.splitlines())} lines/{len(skill)} chars; "
    f"maintainer={len(maintainer_files)} files/{maintainer_bytes} bytes; fast_check={fast_command_count} commands"
)
