"""Keep the always-loaded Skill body lean and domain retrieval selective."""

import os
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
skill = (ROOT / "SKILL.md").read_text(encoding="utf-8")
failures: list[str] = []

if len(skill.splitlines()) > 180:
    failures.append("SKILL.md exceeds 180 lines")
if len(skill) > 8500:
    failures.append("SKILL.md exceeds 8,500 characters")
if not any(marker in skill for marker in ("Load one stage reference", "每次只加载一个有效切片")):
    failures.append("SKILL lost progressive-disclosure instruction")
if "scripts/query_domain.py --domain <pack>" not in skill:
    failures.append("SKILL loads full domain coverage instead of one compact record")

probe = subprocess.run(
    [sys.executable, str(ROOT / "scripts/query_domain.py"), "--domain", "oa"],
    cwd=ROOT,
    text=True,
    encoding="utf-8",
    capture_output=True,
    check=False,
    env={**os.environ, "PYTHONIOENCODING": "cp1252"},
)
if probe.returncode != 0:
    failures.append("OA compact-domain query failed: " + probe.stdout + probe.stderr)
elif len(probe.stdout) > 5000:
    failures.append("OA compact-domain query exceeds 5,000 characters")
for marker in (
    "domain_id: oa", "maturity: contract_tested", "production_claim: prohibited",
    "KS-OA-WEAVER-WHITEPAPER", "KS-OA-DINGTALK-OSS", "KS-OA-FEISHU-OSS",
):
    if marker not in probe.stdout:
        failures.append(f"OA compact-domain query misses {marker!r}")

with tempfile.TemporaryDirectory(prefix="ads-runtime-budget-") as temp_name:
    archive_path = Path(temp_name) / "runtime.zip"
    package = subprocess.run(
        [
            sys.executable, str(ROOT / "maintainer/tools/build_runtime_package.py"),
            "--output", str(archive_path), "--check",
        ],
        cwd=ROOT, text=True, encoding="utf-8", capture_output=True, check=False,
    )
    if package.returncode != 0:
        failures.append("runtime package build failed: " + package.stdout + package.stderr)
    elif not archive_path.is_file():
        failures.append("runtime package archive was not created")
    else:
        with zipfile.ZipFile(archive_path) as archive:
            names = archive.namelist()
        polluted = [name for name in names if "__pycache__" in name or name.endswith((".pyc", ".pyo"))]
        if polluted:
            failures.append("runtime package contains generated bytecode: " + ", ".join(polluted))
        if len(names) > 101:  # max 100 source files + one generated manifest
            failures.append(f"runtime zip contains {len(names)} entries; expected <=101")

if failures:
    raise SystemExit("\n".join(failures))
print(f"PASS: SKILL stays within {len(skill.splitlines())} lines/{len(skill)} chars and domain retrieval is selective")
